### ISSUE TITLE
Make image grid stable while rendering images

### ISSUE THREAD

**Issue by msk4862** [msk4862/Copyright-free-image-search#2]
**Problem:** Currently when images are being rendered on they page they fluctuate a lot.
**Task:** Use some technique to make this image rendering more smooth on the page.

**Comment by MrBartusek** [comment]
@msk4862 I'd love to work on that!

**Comment by msk4862** [comment]
@MrBartusek go ahead!

**Comment by msk4862** [comment]
Track your progress here @MrBartusek

**Comment by MrBartusek** [comment]
@msk4862  I am familiarizing with the codebase right now, I think I will delay doing this for a bit, I see a bigger issue there.

Basically, if want to run the project dry without API keys it doesn't work at all. I would need to request an API key from pixels to even run this thing. I will right now work on handling configuration a little bit better and work on this right after this. Hope that's not a problem!

**Comment by msk4862** [comment]
@MrBartusek  What type of changes are you thinking to handle configuration better? <br/>Can you elaborate a little?

**Comment by MrBartusek** [comment]
@msk4862 First of all, don't crash backend when there are no API keys or API fails, just send a placeholder. Right now website would crash if the external API will fail.

Then I was thinking about adding some more intuitive way of handling external APIs for example, some config file that would keep a list of services rather than hard-coding them

I am still not sure how to pull that off, I will just make it and see how it turns out

**Comment by MrBartusek** [comment]
BTW @msk4862 from yesterday if you wish to your repository count towards hacktoberfest you need to add `hacktoberfest` topic to repo https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by msk4862** [comment]
@MrBartusek Oh okay.

**Comment by msk4862** [comment]
@MrBartusek how are you reading `.env` file without `dotenv` in `server-side`?

**Comment by MrBartusek** [comment]
@msk4862 I removed .env file support since the app can run without it and all of the "important" variables are API keys which shouldn't be kept here

I can re-add it ofc

**Comment by msk4862** [comment]
@MrBartusek `.env` file is local only, It won't be uploaded. But no problem, I'll do it

**Comment by MrBartusek** [comment]
I was thinking about that issue and i don't know how to fix that, i am not working on it anymore

**Comment by msk4862** [comment]
@MrBartusek okay no problem.
